src/objects/Aggreement__c.object
<CustomObject>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Aggreements</relationshipLabel>
        <relationshipName>Aggreements</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dealer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Dealer</label>
        <referenceTo>Dealer__c</referenceTo>
        <relationshipLabel>Aggreements</relationshipLabel>
        <relationshipName>Aggreements</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NofemployeeAssigned__c</fullName>
        <label>NofemployeeAssigned</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Aggreement</label>
    <nameField>
        <label>Aggreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aggreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Company__c.object
<CustomObject>
    <fields>
        <fullName>TotalNoofEmployeeAvailable__c</fullName>
        <label>TotalNoofEmployeeAvailable</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Dealer__c.object
<CustomObject>
    <label>Dealer</label>
    <nameField>
        <label>Dealer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestAggreement.cls
@isTest
public class TestAggreement {
    @isTest static void Tester()
    { List<Aggreement__c> L1=new List<Aggreement__c>();
     
       Dealer__c D1=new Dealer__c(Name='Zoho');
         insert D1;
       company__c c1=new Company__C(Name='Infosys',TotalNoofEmployeeAvailable__c=5100);
         Insert C1;
       Test.startTest();
       Aggreement__c a=new Aggreement__c(Name='Agg1',NofemployeeAssigned__c=100,Company__c=c1.Id,Dealer__c=D1.id);
     
         insert a; 
       L1.add(a);
     
      AggreementHandler.Agg(L1,null);
      AggreementHandler.Agg1(null,L1);
        
        
       
        
    }
}