src/objects/Aggreement__c.object
<CustomObject>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>Aggreements</relationshipLabel>
        <relationshipName>Aggreements</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dealer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Dealer</label>
        <referenceTo>Dealer__c</referenceTo>
        <relationshipLabel>Aggreements</relationshipLabel>
        <relationshipName>Aggreements</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NofemployeeAssigned__c</fullName>
        <label>NofemployeeAssigned</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Aggreement</label>
    <nameField>
        <label>Aggreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aggreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Company__c.object
<CustomObject>
    <fields>
        <fullName>TotalNoofEmployeeAvailable__c</fullName>
        <label>TotalNoofEmployeeAvailable</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Dealer__c.object
<CustomObject>
    <fields>
        <fullName>NofEmployeeCurrWorking__c</fullName>
        <label>NofEmployeeCurrWorking</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Dealer</label>
    <nameField>
        <label>Dealer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AggreementHandler.cls
public class AggreementHandler
{
 Public static void Agg(List<Aggreement__c> sagar,List<Aggreement__c> ss)
 { 

    set<ID> IDS=new set<ID>();
    List<Company__c> ll=new List<Company__c>();
    List<Dealer__c> L2=new List<Dealer__c>();

   
    for(Aggreement__c a1:sagar ) 
        {
            IDS.add(a1.id);
        }

    system.debug('Ids are'+IDS);
  
    
     List<Aggreement__c> newList=[Select id,NofemployeeAssigned__c,company__r.id,company__r.TotalNoofEmployeeAvailable__c,Dealer__r.NofEmployeeCurrWorking__c from Aggreement__c where id in:IDS ];
     system.debug(newlist);
     for(Aggreement__c cc:newList)
    {      
             
             Decimal temp =cc.Company__r.TotalNoofEmployeeAvailable__c-cc.NofemployeeAssigned__c;
             system.debug(temp);
             if(cc.Dealer__r.NofEmployeeCurrWorking__c!=null)
             {   Decimal temp1=cc.Dealer__r.NofEmployeeCurrWorking__c;
                 ll.add(new Company__c(id = cc.Company__r.id , TotalNoofEmployeeAvailable__c=temp));
                 L2.add(new Dealer__c (id=cc.Dealer__r.id, NofEmployeeCurrWorking__c= temp1 + cc.NofemployeeAssigned__c));
              system.debug(temp1);
              }
             else
                 L2.add(new Dealer__c (id=cc.Dealer__r.id, NofEmployeeCurrWorking__c=cc.NofemployeeAssigned__c));
        
  
    }
     
    update ll; 
    Update L2;
    system.debug(ll);

}

    
    
       Public static void Agg1(List<Aggreement__c> sagar,List<Aggreement__c> ss)
 { 

    set<ID> IDS=new set<ID>();
    List<Company__c> ll=new List<Company__c>();
    List<Dealer__c> L2=new List<Dealer__c>();

    
    for(Aggreement__c a1:ss) 
        {
            IDS.add(a1.id);
        }

     system.debug('Ids are'+IDS);

     List<Aggreement__c> newList=[Select id,NofemployeeAssigned__c,company__r.id,company__r.TotalNoofEmployeeAvailable__c,Dealer__r.NofEmployeeCurrWorking__c from Aggreement__c where id in:IDS];
     system.debug(newlist);
     for(Aggreement__c cc:newList)
    {       
             if(cc.NofemployeeAssigned__c!=null && cc.Dealer__r.NofEmployeeCurrWorking__c!=null)
             {
             Decimal temp =cc.Company__r.TotalNoofEmployeeAvailable__c+cc.NofemployeeAssigned__c;   
             Decimal temp1=cc.Dealer__r.NofEmployeeCurrWorking__c-cc.NofemployeeAssigned__c;
             ll.add(new Company__c(id = cc.Company__r.id ,TotalNoofEmployeeAvailable__c=temp));
             L2.add(new Dealer__c (id=cc.Dealer__r.id, NofEmployeeCurrWorking__c=temp1 )); 
             system.debug(temp);
             }
          
    }
     
    update ll; 
    Update L2;
  //  a072v00001AinTUAAZ

}

 
 
}